### ISSUE TITLE
Thumbnails only generated for storage uploads

### ISSUE THREAD

**Issue by Flemmli97** [Satellite-im/Warp#244]
The current implementation of thumbnails for files only sets the thumbnail for `ConstellationCmd::UploadFiles` which for uplink means this only happens when a user uploads a file on the files page.
If a user does it via chat the thumbnails never gets set still see `warp_rg_ipfs::store::message::MessageStore#attach`

**Comment by dariusc93** [comment]
`RayGun::attach` does support `Location`, which can reference items in `Constellation` or on disk when choosing a file to attach and send. Until #230 is merged (although it will only support images for now), a work around would be to upload to constellation first and use `Location::Constellation` while pointing to the file(s) path in constellation. Once the PR is merged in and `Location::Disk` is used, it would go through a similar process in which it would attempt to generate a thumbnail when uploading/attaching a file.

Relates to #169
