### ISSUE TITLE
iOS support 

### ISSUE THREAD

**Issue by jkelleyrtp** [Satellite-im/Warp#260]
Currently Warp can't build for iOS targets due to its use of `natpmp` which relies on native sockets. Apple has decided to lockdown native socket support so this low-level functionality cannot be used directly via `natpmp`. We should either look for an alternative crate to `natpmp` or extend it with iOS (and potentially Android) support via iOS frameworks.

**Comment by dariusc93** [comment]
Warp doesnt use natpmp directly but is depended on in a upstream dependency, however in a upcoming change, i will have it exclude natpmp for ios and default to using igd, which should build and work fine it.

**Comment by dariusc93** [comment]
This was resolved with a dependency update upstream.
