### ISSUE TITLE
Implement a better query system for PocketDimension

### ISSUE THREAD

**Issue by tooshel** [Satellite-im/Warp#27]
Current, the `QueryBuilder` that is used for `PocketDimension` feels generic and would be missing out on things like complete filtering, comparison, etc. While may be simple enough to get by in simple searches in any cache/db system, some implementations may want to perform more complex queries. 

Not wanting to make it extremely complex or very simple, we may want to look into adapting several functionality into the query system that can be extended into `PocketDimension` that would allow for flexibility. 

Currently, it may be better to have the query system that would be json-style, similar to nosql queries like mongodb. This would leave it up to the extension to implement their owns system or possibly use our own system base on this style and collect and use the data that way.

**Comment by dariusc93** [comment]
Blocked pending #63

**Comment by dariusc93** [comment]
Closing since https://github.com/Satellite-im/Warp/issues/63 would likely improve on this.
