### ISSUE TITLE
add capability to record calls to warp-blink-wrtc

### ISSUE THREAD

**Issue by sdwoodbury** [Satellite-im/Warp#273]
we want to record audio/video tracks to an .mp4 file. From my reading I believe the `moov` box should be configured for an empty `mdat` box, and the data be added to the file in fragments. This technique allows writing to the file without having to know about the entire "presentation" beforehand.

**Comment by dariusc93** [comment]
If calls are to be recorded, shouldnt there be some type of indication to alert when somebody in the call is recording? Should users have permission markings of sort to allow calls to be recorded in the first place (eg direct calls both users have to consent, while in group calls, the creator of the group has to allow it or whenever a permission system is implemented to grant/revoke permissions to participants)?

**Comment by sdwoodbury** [comment]
> If calls are to be recorded, shouldnt there be some type of indication to alert when somebody in the call is recording? Should users have permission markings of sort to allow calls to be recorded in the first place (eg direct calls both users have to consent, while in group calls, the creator of the group has to allow it or whenever a permission system is implemented to grant/revoke permissions to participants)?

I like the idea of having both participants consent to recording  for direct calls, and using a permission system for group calls. Such a system could be as simple as: host can record (y/n) and other participants can record (y/n).
