### ISSUE TITLE
Implement Group Messaging

### ISSUE THREAD

**Issue by tooshel** [Satellite-im/Warp#30]
This is from https://satellite-im.atlassian.net/browse/WARP-121

**Comment by tooshel** [comment]
This is an ongoing effort that will span a few weeks . . . can we break it up into smaller chucks?

**Comment by dariusc93** [comment]
Yea this would get split up into 2. One would be smaller group messaging (eg been 3 or more people) while the other would be a bit larger (eg community-style group). The former would be implemented first to lay out the ground work then would extend out to permissions, group and user management (which would be a refactor into the group interface), etc.
