### ISSUE TITLE
raygun: Support members adding other members to a group

### ISSUE THREAD

**Issue by dariusc93** [Satellite-im/Warp#386]
The current group implementation only allows the creator of the group to add/remove members, but the owner may want to allow anyone to add members. In this case, since there is no permissions in place for groups (which will be separate from this issue), we could split the group multiple types:

1. `Group` - For now, will be the same as `ClosedGroup` but may change in the future to recipient a larger scale group (eg community style groups)
2. `ClosedGroup` - Only the owner/creator of the group will be able to add and remove members (default)
3. `OpenGroup` - Allow the members of the group to add others to the group, with the owner being able to remove them.

We can add a new trait function either called:
- `RayGun::set_group_type` where it would accept the conversation id and an enum called `GroupType` which would be as follows
```rust
pub enum GroupType {
    Open,
    Closed
}
```

- `RayGun::set_conversation_type` which would accept the conversation id and allow setting `ConversationType` with `OpenGroup` and `ClosedGroup` being apart of `ConversationType` to be used in the function. 

We can also modify `RayGun::create_group_conversation` to accept a option to create a open or closed group. 

Note:
- If a conversation is already set as group and toggled to be `OpenGroup`, the creator can only then switch it to `ClosedGroup`.
- Will require ignoring recipient list when signing/verifying the conversation document if the group is opened since the current implementation use the list when signing/verifying (to be sure that the list cannot be tampered unless approved by the creator of the conversation)
- The conversation document should include a `exclude` or `block` list by the creator to prevent adding members who the creator of the group has blocked. (Should only be effective for `OpenGroup` since `Group`/`ClosedGroup` should automatically remove them if they are blocked)
- The former function would be preferred to prevent confusion and possible conflicts in the future.

**Comment by InfamousVague** [comment]
It would be ideal to just default to a permissions-enabled group. I think it would be frustrating if a user were to make a group not realizing it was Closed and then could not add a moderator in later. I think I understand the use case for these groups where you allow anyone to add users, but I think it would be better to just have this functionality be a setting any admin / owner can set on the group "allow anybody to add users <bool>".

**Comment by dariusc93** [comment]
> It would be ideal to just default to a permissions-enabled group. I think it would be frustrating if a user were to make a group not realizing it was Closed and then could not add a moderator in later. I think I understand the use case for these groups where you allow anyone to add users, but I think it would be better to just have this functionality be a setting any admin / owner can set on the group "allow anybody to add users ".

As stated above, this is issue is separate from permissions and in itself would be a separate issue for group chat.

**Comment by zeenix** [comment]
> > It would be ideal to just default to a permissions-enabled group. I think it would be frustrating if a user were to make a group not realizing it was Closed and then could not add a moderator in later. I think I understand the use case for these groups where you allow anyone to add users, but I think it would be better to just have this functionality be a setting any admin / owner can set on the group "allow anybody to add users ".
> 
> As stated above, this is issue is separate from permissions and in itself would be a separate issue for group chat.

Yeah but what @InfamousVague is saying (and I agree) is that we shouldn't have a open and closed group differentiation and just have a simple setting for allowing/disallowing non-admins adding members (this part would of course be a separate issue).

**Comment by InfamousVague** [comment]
> > > It would be ideal to just default to a permissions-enabled group. I think it would be frustrating if a user were to make a group not realizing it was Closed and then could not add a moderator in later. I think I understand the use case for these groups where you allow anyone to add users, but I think it would be better to just have this functionality be a setting any admin / owner can set on the group "allow anybody to add users ".
> > 
> > 
> > As stated above, this is issue is separate from permissions and in itself would be a separate issue for group chat.
> 
> Yeah but what @InfamousVague is saying (and I agree) is that we shouldn't have a open and closed group differentiation and just have a simple setting for allowing/disallowing non-admins adding members (this part would of course be a separate issue).

precisely

**Comment by zeenix** [comment]
#416 implements a simple open and closed group. Currently it only allows setting the group type at creation time only. I think this is sufficient for now. I took the liberty of splitting 2 main follow-ups from this into their own issues:

* #417 
* #418 

So this can by closed by #416.
