### ISSUE TITLE
Investigate Memory Usage

### ISSUE THREAD

**Issue by dariusc93** [Satellite-im/Warp#67]
It was recently reported of high memory usage. After doing my own check with 4 instances within a 16 hour span with each having different connection limits (more of a side test but not related to the issue itself), it looks like 2 of the 4 experience high memory usage of avg 1.2GB while running with the other two increased slightly but didnt exceed beyond the average 300MB (with some decrease) with the limits set not having an impact on the usage.

**Comment by dariusc93** [comment]
Memory usage was mostly pinned upstream, some due to reserved allocation. This will be addressed soon to reduce the allocation upstream

**Comment by dariusc93** [comment]
This should partially be correctly with #133 but the rest will come from an update to upstream dependencies.

**Comment by tooshel** [comment]
@dariusc93 Can we close this out now?
