### ISSUE TITLE
Improve on FileType

### ISSUE THREAD

**Issue by dariusc93** [Satellite-im/Warp#70]
In Constellation, File has whats called `FileType` which represents the type of file it may be. Right now, there are only 4 options within the enum, but should implement several other common media type, however the list should not be extensive. This could probably get replaced with `mime` crate with an upper layer to perform checks on the file type to match it to a specific mime or possibly checking the header of the file to match it (eg images usually have a signature in its header that determine if its a specific file, although this should not be the determining factor if this route is taken).

**Comment by InfamousVague** [comment]
This sounds good, could be helpful to be able to get a list of the supported types though, so the UI has the opportunity to render icons easily, or it can use the same approach as warp .
